name: Clojure CI - Unit and Integration Tests

on: [ push ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Install dependencies
        run: lein deps
      - name: Run unit and integration tests
        run: lein test
